image: microsoft/dotnet:latest

stages:
  - build

variables:
  project: "ATH.FileUtility"
  build_path: "Source/$project"

before_script:
  - "cd $build_path"
  - "dotnet restore"

build:
  stage: build
  script:
    - "cd $build_path"
    - "dotnet build"
