image: mono:4.4.0.182

stages:
  - build

variables:
  project: "ATH.FileUtility"
  build_path: "Source"

before_script:
  - "cd $build_path"
  - "dotnet restore"

build:
  stage: build
  script:
    - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="Any CPU" $project.sln
