image: microsoft/dotnet:latest

stages:
  - build

variables:
  project: "ATH.FileUtility"

before_script:
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "Source/$project"
  script:
    - "cd $build_path"
    - "dotnet build"
